// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/aidosgal/alemjobs/internal/storage/postgres/ent/health"
	"github.com/aidosgal/alemjobs/internal/storage/postgres/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	healthMixin := schema.Health{}.Mixin()
	healthMixinFields0 := healthMixin[0].Fields()
	_ = healthMixinFields0
	healthFields := schema.Health{}.Fields()
	_ = healthFields
	// healthDescCreateTime is the schema descriptor for create_time field.
	healthDescCreateTime := healthMixinFields0[0].Descriptor()
	// health.DefaultCreateTime holds the default value on creation for the create_time field.
	health.DefaultCreateTime = healthDescCreateTime.Default.(func() time.Time)
	// healthDescUpdateTime is the schema descriptor for update_time field.
	healthDescUpdateTime := healthMixinFields0[1].Descriptor()
	// health.DefaultUpdateTime holds the default value on creation for the update_time field.
	health.DefaultUpdateTime = healthDescUpdateTime.Default.(func() time.Time)
	// health.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	health.UpdateDefaultUpdateTime = healthDescUpdateTime.UpdateDefault.(func() time.Time)
	// healthDescStatus is the schema descriptor for status field.
	healthDescStatus := healthFields[0].Descriptor()
	// health.DefaultStatus holds the default value on creation for the status field.
	health.DefaultStatus = healthDescStatus.Default.(string)
}
